// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSkul.Models;

#nullable disable

namespace WebSkul.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebSkul.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Working")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Address = "Groove Street",
                            Name = "101",
                            SchoolId = "dfbef93c-220b-4f58-a12d-d444f811f483",
                            Working = 0
                        },
                        new
                        {
                            Id = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Address = "Groove Street",
                            Name = "201",
                            SchoolId = "dfbef93c-220b-4f58-a12d-d444f811f483",
                            Working = 0
                        },
                        new
                        {
                            Id = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Address = "Groove Street",
                            Name = "301",
                            SchoolId = "dfbef93c-220b-4f58-a12d-d444f811f483",
                            Working = 0
                        },
                        new
                        {
                            Id = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Address = "Groove Street",
                            Name = "401",
                            SchoolId = "dfbef93c-220b-4f58-a12d-d444f811f483",
                            Working = 1
                        },
                        new
                        {
                            Id = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Address = "Groove Street",
                            Name = "501",
                            SchoolId = "dfbef93c-220b-4f58-a12d-d444f811f483",
                            Working = 1
                        });
                });

            modelBuilder.Entity("WebSkul.Models.Evaluation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Grade")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("WebSkul.Models.School", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreationYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = "dfbef93c-220b-4f58-a12d-d444f811f483",
                            Address = "Groove Street",
                            City = "San Andreas",
                            Country = "Los Santos",
                            CreationYear = 2005,
                            Name = "Platzi School",
                            SchoolType = 2
                        });
                });

            modelBuilder.Entity("WebSkul.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "012192df-9cbe-4c0e-8bd1-2095ddb8cf29",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Madd Lawrence Toreno"
                        },
                        new
                        {
                            Id = "01520db3-aae4-4d3f-a41e-29e6441166ad",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Mike Hitori Toreno"
                        },
                        new
                        {
                            Id = "01c53c85-64d6-4512-b108-4d08154cebdd",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Mike Ichigaya Johnson"
                        },
                        new
                        {
                            Id = "04613782-3b17-481d-9fe6-429f8d86ea06",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Big Aoba Smoke"
                        },
                        new
                        {
                            Id = "04aa2634-58df-47a9-8f2a-0508e1437bf3",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Madd Lawrence Zi Mu"
                        },
                        new
                        {
                            Id = "060d9044-d970-4209-b720-3045f606e6f8",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Madd Lawrence Dogg"
                        },
                        new
                        {
                            Id = "0639a485-c217-4105-985a-c6f498606024",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Wu Hitori Toreno"
                        },
                        new
                        {
                            Id = "0842f4be-4208-4363-84cf-7fd6d6fe16b4",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Madd Hikawa Toreno"
                        },
                        new
                        {
                            Id = "09b1d2cc-9404-4560-98da-883c052ffc0e",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Mike Hikawa Zi Mu"
                        },
                        new
                        {
                            Id = "09db8ef1-5cf0-4725-a6df-8d0079c4fff8",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "OG Hitori Zi Mu"
                        },
                        new
                        {
                            Id = "0b0ec2e4-8146-48d2-862a-e6de1a75cc11",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "OG Ichigaya Zi Mu"
                        },
                        new
                        {
                            Id = "033aa716-21e6-40ba-9e2c-8a71dd961401",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Mike Hitori Toreno"
                        },
                        new
                        {
                            Id = "0406eb6b-913d-42af-b71f-10c3c1b91a83",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Madd Yamabuki Loc"
                        },
                        new
                        {
                            Id = "04a50e5c-c983-45e4-9b65-8dc6895606b6",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Madd Yamabuki Smoke"
                        },
                        new
                        {
                            Id = "050c9e08-2d4f-45c8-8305-db5ce5c2f44c",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Madd Lawrence Loc"
                        },
                        new
                        {
                            Id = "052a10b9-91e4-4d25-a9a7-c7f9fa60cab2",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Carl Aoba Loc"
                        },
                        new
                        {
                            Id = "06449b40-706c-4cbe-a844-23ab052e79a7",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Carl Mitake Johnson"
                        },
                        new
                        {
                            Id = "06dcf749-259e-4c75-b1b2-26027101f9e4",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Carl Aoba Toreno"
                        },
                        new
                        {
                            Id = "073927d8-5918-4f61-a349-4d94f0e3e460",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Madd Mitake Toreno"
                        },
                        new
                        {
                            Id = "00ad70de-d4e6-401b-aa6e-679bd136a489",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "OG Hitori Smoke"
                        },
                        new
                        {
                            Id = "01c2113a-e807-4188-b025-9b81d9cbbd9a",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Cesar Hikawa Smoke"
                        },
                        new
                        {
                            Id = "01cc1fbe-e7f0-4225-933b-1ccba5326a3c",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Wu Lawrence Dogg"
                        },
                        new
                        {
                            Id = "01ec4396-9c28-49a2-8dda-822038475e9e",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Cesar Yamabuki Dogg"
                        },
                        new
                        {
                            Id = "01eda820-97f2-416c-b781-bcf321ba196f",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Big Yamabuki Dogg"
                        },
                        new
                        {
                            Id = "030e7341-c0f6-4db7-b9c0-67f628e08f4a",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Wu Lawrence Zi Mu"
                        },
                        new
                        {
                            Id = "039e5ee7-bbdb-4a51-981a-ca0d008ae274",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "OG Hitori Toreno"
                        },
                        new
                        {
                            Id = "03cf0b7a-444a-4285-8597-e960f483fe04",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Carl Aoba Dogg"
                        },
                        new
                        {
                            Id = "04ed297f-89e9-4e48-8089-287100b1afd2",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Carl Hitori Loc"
                        },
                        new
                        {
                            Id = "050d28cd-ccfa-4fe9-8ad1-d100545b5839",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Wu Aoba Toreno"
                        },
                        new
                        {
                            Id = "00291cf2-daa8-4600-8b0d-81ac3f087a15",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Mike Yamabuki Dogg"
                        },
                        new
                        {
                            Id = "0060f6a9-2f51-4335-bd2c-ecf50c64fe90",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Wu Lawrence Dogg"
                        },
                        new
                        {
                            Id = "020e5e49-aaaa-4ab1-a024-fb443a74b2e8",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Carl Aoba Zi Mu"
                        },
                        new
                        {
                            Id = "02e44cf9-0dcb-49f2-a151-953143a78456",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Carl Hikawa Loc"
                        },
                        new
                        {
                            Id = "0310fe2c-5477-409a-897a-fe8693f0aeb7",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Carl Hikawa Dogg"
                        },
                        new
                        {
                            Id = "032cbb7e-9db2-421a-bc04-9cabb619e9bf",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Madd Hikawa Toreno"
                        },
                        new
                        {
                            Id = "04a51fd5-6f4c-4bc1-bf93-1e755230af52",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Carl Aoba Loc"
                        },
                        new
                        {
                            Id = "0635f4dc-194a-4143-93cd-91d5776e0fa5",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "OG Hitori Zi Mu"
                        },
                        new
                        {
                            Id = "08497e09-418f-48cb-baec-b5f260e23715",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Mike Aoba Johnson"
                        },
                        new
                        {
                            Id = "0b40af11-c1e1-43cf-bf11-3cfd15d400e4",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Wu Hikawa Johnson"
                        },
                        new
                        {
                            Id = "0d013268-33e0-4b58-9924-7ad1400a4d19",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Big Hitori Smoke"
                        },
                        new
                        {
                            Id = "0df2361d-680e-46f5-9d79-507ae83e13e9",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Cesar Hikawa Loc"
                        },
                        new
                        {
                            Id = "01c59bc5-f57f-485f-b80e-2892ba6c8694",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Mike Yamabuki Loc"
                        },
                        new
                        {
                            Id = "027e7e0d-4e16-4b84-9760-35e075f81880",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Wu Lawrence Loc"
                        },
                        new
                        {
                            Id = "02a31bda-6afd-41de-9d99-104ec3490cfe",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Wu Aoba Dogg"
                        },
                        new
                        {
                            Id = "03a40cce-ebf7-403c-be85-f92b03bb6df7",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "OG Hitori Johnson"
                        },
                        new
                        {
                            Id = "03c73c5f-f040-414d-b2e3-4b2df26c117a",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Mike Hikawa Zi Mu"
                        },
                        new
                        {
                            Id = "04c5850a-3852-45e3-a77e-82cdb6d4b1ac",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "OG Lawrence Toreno"
                        },
                        new
                        {
                            Id = "04ca7f6c-3b6f-41a2-960b-4ea85eca9f28",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Carl Ichigaya Johnson"
                        },
                        new
                        {
                            Id = "076fc439-72aa-4ef8-98d8-177425b3f3f3",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Carl Yamabuki Loc"
                        });
                });

            modelBuilder.Entity("WebSkul.Models.Subject", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = "1e697cae-5c65-4ca2-9e0c-178472a318b8",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Math"
                        },
                        new
                        {
                            Id = "da6c5f50-b244-4371-9e4d-62401c35ebe0",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "English"
                        },
                        new
                        {
                            Id = "a37c37f1-6199-4570-b46d-f840f5b2045c",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Videogames"
                        },
                        new
                        {
                            Id = "eafbb9c3-0c57-4c49-977c-477a7165e87d",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Music"
                        },
                        new
                        {
                            Id = "f142d1c5-5434-4fe9-9f7a-ed65a2738337",
                            CourseId = "edb1d8f4-0f2c-4a97-b803-23457b057ee0",
                            Name = "Web apps development"
                        },
                        new
                        {
                            Id = "da9e8ed7-b9b8-40af-9fe6-5a6ac67921e8",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Math"
                        },
                        new
                        {
                            Id = "092bfb54-f18e-4d67-bec3-3fe2d6da2903",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "English"
                        },
                        new
                        {
                            Id = "a0fbfc2f-8760-487e-a5da-bd7c1084ed4c",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Videogames"
                        },
                        new
                        {
                            Id = "07e44316-4103-4194-99b8-2a9c9b09d06d",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Music"
                        },
                        new
                        {
                            Id = "1bceb667-a2b5-44ec-89ee-1d5e89452f53",
                            CourseId = "e4433ed8-5e29-4362-870b-482728e3081f",
                            Name = "Web apps development"
                        },
                        new
                        {
                            Id = "e548b5ee-4595-4530-a559-40d446d1aab3",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Math"
                        },
                        new
                        {
                            Id = "f3215bb2-22a8-4f22-bc31-04e1fde9e636",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "English"
                        },
                        new
                        {
                            Id = "2f29498c-f33f-45af-95dd-866a9fa3b3e3",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Videogames"
                        },
                        new
                        {
                            Id = "ae8f2da4-d80a-4b72-8ef0-b170a94ae3ca",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Music"
                        },
                        new
                        {
                            Id = "02c15d7e-680d-4ece-81a5-68438dd9f981",
                            CourseId = "ae5b35f6-d485-4387-98e1-747efd0b7c66",
                            Name = "Web apps development"
                        },
                        new
                        {
                            Id = "680825c1-c6e8-4fac-9b4c-2ebbade212a4",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Math"
                        },
                        new
                        {
                            Id = "91aab658-308b-4e01-9d92-b42dc3d8900c",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "English"
                        },
                        new
                        {
                            Id = "38b87867-8fee-4474-93a5-9d93fc6580e5",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Videogames"
                        },
                        new
                        {
                            Id = "74cd0019-84e5-4f0e-919e-5b4912c60412",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Music"
                        },
                        new
                        {
                            Id = "2c1b218f-fef1-4ffe-8161-dee58e623d02",
                            CourseId = "8bf2bc27-97ed-481c-8b84-cb03dd2dd9f2",
                            Name = "Web apps development"
                        },
                        new
                        {
                            Id = "266f2fdf-80ef-444d-a5c0-0890737e6075",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Math"
                        },
                        new
                        {
                            Id = "dab301b6-80b5-41ae-a966-5be63a847c9d",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "English"
                        },
                        new
                        {
                            Id = "cde296e1-46d6-4f34-8690-b9f8d2dc5832",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Videogames"
                        },
                        new
                        {
                            Id = "5865cddf-5b11-40f2-aad2-9d886e53583d",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Music"
                        },
                        new
                        {
                            Id = "134e7cec-534c-4606-8d0d-650539b39820",
                            CourseId = "7dd213e2-d805-4108-bf7e-8461b3afa6d2",
                            Name = "Web apps development"
                        });
                });

            modelBuilder.Entity("WebSkul.Models.Course", b =>
                {
                    b.HasOne("WebSkul.Models.School", "School")
                        .WithMany("Courses")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("WebSkul.Models.Evaluation", b =>
                {
                    b.HasOne("WebSkul.Models.Student", "Student")
                        .WithMany("EvaluationsList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSkul.Models.Subject", "Subject")
                        .WithMany("EvaluationsList")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("WebSkul.Models.Student", b =>
                {
                    b.HasOne("WebSkul.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebSkul.Models.Subject", b =>
                {
                    b.HasOne("WebSkul.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebSkul.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("WebSkul.Models.School", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("WebSkul.Models.Student", b =>
                {
                    b.Navigation("EvaluationsList");
                });

            modelBuilder.Entity("WebSkul.Models.Subject", b =>
                {
                    b.Navigation("EvaluationsList");
                });
#pragma warning restore 612, 618
        }
    }
}
